mysite/main/urls.py
from django.urls import path
from . import views
from .views import *

urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('questions/', views.questions, name='questions'),
    path('movies/', views.movies, name='movies'),
    path('photos/', views.photos, name='photos'),
    #path('spots/', views.spots, name='spots'),
    #path('spots/create', views.create_spots, name='create_spots'),
    path('spots/', Spots.as_view(), name="Spots"),
    path('spots/<int:pk>', SpotsDetails.as_view(), name='Spots-Post-Detail'),
    path('spots/<int:pk>/comment', AddCommentSpots.as_view(), name='spots-post-comment'),
    path('spots/add', AddSpots.as_view(), name="add-spots"),
    path('spots/delete/<int:pk>', DeleteSpot.as_view(), name="delete-spots"),


]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from register import views as v
from django.views.static import serve
from django.conf.urls import url
from django.conf import settings

urlpatterns = [
    path('', include('main.urls')), 
    path('admin/', admin.site.urls),
    path("register/", v.register, name="register"),
    path('', include("django.contrib.auth.urls")),

    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

mysite/main/models.py
from pyexpat import model
from tabnanny import verbose
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class SpotsPost(models.Model):
    class Meta:
            verbose_name = "Miejscówka"
            verbose_name_plural = "Miejscówki"

    title = models.CharField(max_length=255, verbose_name="Tytuł")
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Autor")
    body = models.TextField(verbose_name = "Treść")

    def get_absolute_url(self):
        return reverse('Spots')

    def __str__(self):
        return self.title + ' | ' + str(self.author)

class SpotsComment(models.Model):
    class Meta:
        verbose_name = "Komentarz do miejscówek"
        verbose_name_plural = "Komentarze do miejscówek"

    post = models.ForeignKey(SpotsPost, related_name="spotscomments", on_delete=models.CASCADE, verbose_name="")
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Autor")
    body = models.TextField(verbose_name="Treść")
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.post) + ' | ' + str(self.author)

mysite/register/models.py
from django.db import models

# Create your models here.

mysite/main/forms.py
from tkinter import Widget
from django import forms
from .models import *


class PostSpotForm(forms.ModelForm):
    class Meta:
        model = SpotsPost
        fields = ('title', 'author', 'body')
        
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'author': forms.TextInput(attrs={'class': 'form-control', 'value':'','id':'user', 'type':'hidden'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
        }

        labels = {
            'title':'Tytuł',
            'body': 'Treść',
        }

class CommentSpotForm(forms.ModelForm):
    class Meta:
        model = SpotsComment
        fields = ('author', 'body')
        
        widgets = {
            'author': forms.TextInput(attrs={'class': 'form-control', 'value':'','id':'user', 'type':'hidden'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
        }

        labels = {
            'body': 'Treść',
        }

mysite/main/views.py
from msilib.schema import ListBox
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, DeleteView
from .models import *
from .forms import *

# Create your views here.

def index(response):
    return render(response, "main/base.html", {})

def home(response):
    return render(response, "main/home.html", {})

def questions(response):
    return render(response, "main/questions.html", {})

def movies(response):
    return render(response, "main/movies.html", {})

def photos(response):
    return render(response, "main/photos.html", {})

class Spots(ListView):
    model = SpotsPost
    template_name = 'main/spots.html'

class SpotsDetails(DetailView):
    model = SpotsPost
    template_name = 'main/spots_post_detail.html'

class AddSpots(CreateView):
    model = SpotsPost
    form_class = PostSpotForm
    template_name = 'main/create_spots.html'
    #fields = ('title', 'body')

class AddCommentSpots(CreateView):
    model = SpotsComment
    form_class = CommentSpotForm
    template_name = 'main/comment_spots.html'

    def form_valid(self, form):
        form.instance.post_id = self.kwargs['pk']
        return super().form_valid(form)
    success_url = reverse_lazy('Spots')

class DeleteSpot(DeleteView):
    model = SpotsPost
    template_name = 'main/delete_spots.html'
    success_url = reverse_lazy('Spots')

mysite/register/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def register(response):
    if response.method == "POST":
        form = UserCreationForm(response.POST)
        if form.is_valid():
            form.save()
        
        return redirect("/home")
    else:
        form = UserCreationForm()

    return render(response, "register/register.html", {"form":form})

mysite/main/templates/main/base.html
<!-- base.html -->
<!doctype html>
<html>
<head>
	<style type="text/css">
		.sidenav {
			height:100%;
			width:160px;
			position: fixed;
			z-index:1;
			top:0;
			left:0;
			background-color:#111;
			overflow-x: hidden;
			padding-top: 20px;
		}    

                .sidenav a {
			padding:6px 8px 6px 16px;
			text-decoration: none;
			font-size:25px;
			color: #818181;
			display:block;
		}  
  
                .sidenav a:hover{
			color:#f1f1f1;
		}     

                .main{
			margin-left:160px;
			padding: 0px 10px;
		}   
    </style>
 
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
 
	<title>{% block title %}Deskorolka{% endblock %}</title>
</head>
 
<body>
	<div class="sidenav">
        {% if user.is_authenticated %}
            <p><a href="/logout">Wyloguj</a></p>
        {% else %}
            <p><a href="/login">Zaloguj</a></p>
        {% endif %}
		<a href="/home">Strona główna</a>
		<!-- <a href="/questions">Pytania</a>
		<a href="/movies">Filmy</a>
		<a href="/photos">Zdjęcia</a> -->
		<a href="/spots">Miejscówki</a>
	</div>
 
	<div id="content" name="content" class="main">
		<div class="row justify-content-center">
			<div class="col-8">
                {% if user.is_authenticated %}
                    <h1 class="mt-2">Witaj, {{user.get_username}}</h1>
                {% else %}
                    <h1 class="mt-2">Forum deskorolkowe</h1>
                {% endif %}
				
				<hr class="mt-0 mb-4">
                {% block content %}
                {% endblock %}
			</div>
		</div>
	</div>
 
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

mysite/main/templates/main/comment_spots.html
{% extends 'main/base.html' %}
{% block title %} Dodaj komentarz {% endblock %}
{% block content %}
    {% if user.is_authenticated %}
    <div class="form-group">
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button class="btn btn-secondary">Opublikuj</button>
    </div>
        
    <script>
        var name ='{{ user.id }}';
        document.getElementById('user').value = name;

        var post ='{{ spotspost.pk }}';
        document.getElementById('post').value = post;

    </script>

    {% else %}
        <h1>Zaloguj się, aby dodać miejscówkę!</h1>
    {% endif %}

{% endblock %}

mysite/main/templates/main/create_spots.html
{% extends 'main/base.html' %}
{% block title %} Dodaj miejscówkę {% endblock %}
{% block content %}
    {% if user.is_authenticated %}
    <div class="form-group">
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button class="btn btn-secondary">Opublikuj</button>
    </div>
        
    <script>
        var name ='{{ user.id }}';
        document.getElementById('user').value = name;
    </script>

    {% else %}
        <h1>Zaloguj się, aby dodać miejscówkę!</h1>
    {% endif %}

{% endblock %}

mysite/main/templates/main/delete_spots.html
{% extends 'main/base.html' %}
{% block title %} Usuń miejscówkę {% endblock %}
{% block content %}
    {% if perms.main.delete_spotspost or user == spotspost.author %}
    <div class="form-group">
        <form method="POST">
            {% csrf_token %}
            
            <button class="btn btn-secondary">Usuń post</button>
    </div>

    {% else %}
        <h1>Nie masz uprawnień.</h1>
    {% endif %}

{% endblock %}

mysite/main/templates/main/home.html
{% extends 'main/base.html' %}
{% block title %}Forum deskorolkowe {% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        <p>Aby uniknąc niepotrzebnego spamu zamieszaj treści w odpowdnich sekcjach:</p>
        <ol>
            <!-- <li><b>Pytania</b></li>
            <p>W tej sekcji możesz śmiało zadawać różne pytania odnosnie sprzętu, porad, czy szukac ludzi do wspólnej jazdy.</p>
            <li><b>Filmy</b></li>
            <p>Ta sekcja jest przeznaczona na publikowanie swoich lub innych filmów związanych z deskorolką.</p>
            <li><b>Zdjęcia</b></li>
            <p>Ta sekcja jest przeznaczona na publikowanie swoich lub innych zdjęć związanych z deskorolką.</p> -->
            <li><b>Miejscówki</b></li>
            <p>W tej skecji mozna umieszczać dane lokalizacyjne skateparków lub miejsc, gdzie można jeździć na deskorolce.</p>
        </ol>
    {% else %}
        <h1>Witaj!</h1>
        <p>Forum deskorolkowe jest miejscem, gdzie możesz swobodnie zadawać pytania, publikować treści oraz zawierać przyjaźnie na lata!</p>
        <p>Niezalogowani użytkownicy mogą jedynie przeglądać dostępne treści.</p>
        <p>Aby w pełni korzystać z forum zaloguj się lub stwórz konto!</p>
    {% endif %}

{% endblock %}

mysite/main/templates/main/index.html
<!-- base.html -->
<!doctype html>
<html>
<head>
	<style type="text/css">
		.sidenav {
			height:100%;
			width:160px;
			position: fixed;
			z-index:1;
			top:0;
			left:0;
			background-color:#111;
			overflow-x: :hidden;
			padding-top:20px;
		}    

                .sidenav a {
			padding:6px 8px 6px 16px;
			text-decoration: none;
			font-size:25px;
			color: #818181;
			display:block;
		}  
  
                .sidenav a:hover{
			color:#f1f1f1;
		}     

                .main{
			margin-left:160px;
			padding: 0px 10px;
		}   
    </style>
 
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
 
	<title>{% block title %}Tim's Site{% endblock %}</title>
</head>
 
<body>
	<div class="sidenav">
		<a href="/">Home</a>
		<a href="/create">Create</a>
		<a href="/2">View</a>
	</div>
 
	<div id="content" name="content" class="main">
		<div class="row justify-content-center">
			<div class="col-8">
				<h1 class="mt-2">My Site</h1>
				<hr class="mt-0 mb-4">
				{% block content %}
				{% endblock %}
			</div>
		</div>
	</div>
 
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

mysite/main/templates/main/movies.html
{% extends 'main/base.html' %}
{% block title %} Filmy {% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        Tutaj będzie przycisk DODAJ FILM
    {% endif %}

    <p>Filmy</p>

{% endblock %}

mysite/main/templates/main/photos.html
{% extends 'main/base.html' %}
{% block title %} Zdjęcia {% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        Tutaj będzie przycisk DODAJ ZDJĘCIE
    {% endif %}

    <p>Zdjęcia</p>

{% endblock %}

mysite/main/templates/main/questions.html
{% extends 'main/base.html' %}
{% block title %} Pytania {% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        Tutaj będzie przycisk DODAJ PYTANIE
    {% endif %}

    <p>Pytanka</p>

{% endblock %}

mysite/main/templates/main/spots.html
{% extends 'main/base.html' %}
{% block title %} Miejscówki {% endblock %}
{% block content %}
    {% if user.is_authenticated %}
    <a href="{% url 'add-spots' %}">
        <button class="btn btn-secondary">
            Dodaj miejscówkę!
        </button>
    </a>
    </br>
    </br>
    {% endif %}

    {% for post in object_list %}
    <hr>
        <p>
            <b>{{post.author}}</b>
            </br>
            <a href="{% url 'Spots-Post-Detail' post.pk %}">
                {{post.title}}
            </a>
            </br>
            {% if perms.main.delete_spotspost or user == post.author %}
            <a href="{% url 'delete-spots' post.pk %}">
                (Usuń)
            </a>
            {% endif %}
        </p>
    <hr>
    {% endfor %}

{% endblock %}

mysite/main/templates/main/spots_post_detail.html
{% extends 'main/base.html' %}
{% block title %} Miejscówki {% endblock %}
{% block content %}

        <p>
            Autor: <b>{{object.author}}</b>
            </br>
            Tytuł: <u>{{object.title}}</u>
            </br>
            </br>
            {{object.body}}
        </p> 

        <hr>

        <p>
            <b>Komentarze:</b>
            </br>
            {% if not spotspost.spotscomments.all %}
                Brak komentarzy
            {% else %}
                {% for comment in spotspost.spotscomments.all %}
                    <hr>
                    <strong>
                        {{comment.author}}
                    </strong>
                    </br>
                    <i>{{comment.date}}</i>
                    </br>
                    {{comment.body}}
                    </br>
                    <hr>
                {% endfor %}
            {% endif %}
            </br>
            {% if user.is_authenticated %}
            <a href="{% url 'spots-post-comment' spotspost.pk %}">
                <button class="btn btn-secondary">Dodaj Komentarz</button>
            </a>
            {% endif %}
        </p>





    

{% endblock %}

mysite/register/templates/register/register.html
{% extends "main/base.html" %}

{% block title %} 
    Stwórz konto 
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    {% if user.is_authenticated %}
        <h1>Jesteś zalogowany, nie musisz robić kolejnego konta.</h1>
    {% else %}
        <form method="POST" class="form-group">
            {% csrf_token %}
            {{form|crispy}}
            <button type ="submit" class="btn btn-success">Zarejestruj się</button>
        </form>
    {% endif %}
{% endblock %}